name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Modules/apigee/proxies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.APIGEE_SA_KEY }}'
          token_format: 'access_token'

      - name: Install apigeecli
        working-directory: .
        run: |
          curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
          echo "$HOME/.apigeecli/bin" >> $GITHUB_PATH

      - name: Deploy Shared Flow - Spike Arrest
        working-directory: Modules/apigee/sharedflows/sf-spikearrest
        run: |
          apigeecli sharedflows create bundle \
            -f sharedflowbundle \
            -n sf-spikearrest \
            -o internship-439613 \
            -t ${{ steps.auth.outputs.access_token }}
          apigeecli sharedflows deploy \
            -n sf-spikearrest \
            -e eval \
            -o internship-439613 \
            --sa apigee-github-deployer@internship-439613.iam.gserviceaccount.com \
            -t ${{ steps.auth.outputs.access_token }} \
            --ovr

      - name: Deploy Shared Flow - Raise Fault
        working-directory: Modules/apigee/sharedflows/sf-raisefault
        run: |
          apigeecli sharedflows create bundle \
            -f sharedflowbundle \
            -n sf-raisefault \
            -o internship-439613 \
            -t ${{ steps.auth.outputs.access_token }}
          apigeecli sharedflows deploy \
            -n sf-raisefault \
            -e eval \
            -o internship-439613 \
            --sa apigee-github-deployer@internship-439613.iam.gserviceaccount.com \
            -t ${{ steps.auth.outputs.access_token }} \
            --ovr

      - name: Build and Deploy Apigee Proxy
        run: |
          mvn clean install -Peval \
            -Dorg=internship-439613 \
            -Denv=eval \
            -Dbearer="${{ steps.auth.outputs.access_token }}" \
            -Dapigee.options=override
