name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Modules/apigee/proxies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Deploy Apigee Proxy
        run: |
          mvn clean install -Peval \
            -Dorg=apt-advantage-495505-k1 \
            -Denv=eval \
            -Dbearer="ya29.a0AT3oNZ_CbQkc2LjRzu0i3aeCChxloSzUOoJfan337e9aZXL1Fe2c_jfMiaG3F_tKmF6NfG9q_Uk8xZLvFq6lHE7MPUENh21ja5d5fWO6Jr73Qv-gBJfXINbYHuR3N8VIh4uQUd-zWcoCqvePeOPUMNbtgk0KyWJwr6U3mohAEtPygUwEaMKI9piX8YTRTvsdgd7joIzFaue6aCgYKAS0SARISFQHGX2MiZk8sbELj3FiR71e2pznj1Q0211" \
            -Dapigee.options=override
