name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Modules/apigee/proxies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Deploy Apigee Proxy
        run: |
          mvn clean install -Peval \
            -Dorg=apt-advantage-495505-k1 \
            -Denv=eval \
            -Dbearer="ya29.a0AT3oNZ93L0CCzRC0wTarh66Jup0sq3O6Nd0Y07GB0lDdnlgDOL8m5hZ852aWxV7vnQVLeelHe3lA91uohOzEEa9_0QLFOwKFyJWhG9qj4s6QPApW4op-evGjTIn3HQdj0ZJhjNIft_0D7si7kpC4fzyObUx2K8me6snifb06edjG-JWcgj4APFB0BJSmTTZ-J3smKlsCzjBhaCgYKAfYSARISFQHGX2Mi6_OJw4eP87OT4bGHhzsSQw0211" \
            -Dapigee.options=override
